### ISSUE TITLE
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'other'

### ISSUE THREAD

**Issue by xialei1020** [JingtongSu/sanity-checking-pruning#1]
Traceback (most recent call last):
  File "LT_prune.py", line 299, in <module>
    main()
  File "LT_prune.py", line 208, in main
    mask = weight_copy.gt(thre).float().cuda()
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'other'

I used pytorch 1.1.0 for gpu on GTX 2080Ti running LT_prune.py

**Comment by JingtongSu** [comment]
Thanks for your question! This error seems to be caused by the GPU device setup. Please check your PyTorch CUDA environment, or you can specify the device you want to use by replacing .cuda with .to(your device).
